import { Shield, AlertTriangle, Database, Sparkles, Users } from "lucide-react";

interface Props {
  source: "official" | "estimated" | "historical" | "ai-generated" | "user-reported";
  className?: string;
}

const sourceConfig = {
  official: {
    icon: Shield,
    label: "Official Data",
    color: "text-emerald-600 bg-emerald-50 border-emerald-200",
    tooltip: "Data sourced from official government/counselling authority websites",
  },
  historical: {
    icon: Database,
    label: "Historical",
    color: "text-blue-600 bg-blue-50 border-blue-200",
    tooltip: "Data from previous counselling years based on publicly available records",
  },
  estimated: {
    icon: AlertTriangle,
    label: "Estimated",
    color: "text-amber-600 bg-amber-50 border-amber-200",
    tooltip: "Estimated based on historical trends and available data. May not reflect exact current values.",
  },
  "ai-generated": {
    icon: Sparkles,
    label: "AI Estimate",
    color: "text-purple-600 bg-purple-50 border-purple-200",
    tooltip: "Generated by AI based on available data patterns. For reference only.",
  },
  "user-reported": {
    icon: Users,
    label: "User Reported",
    color: "text-orange-600 bg-orange-50 border-orange-200",
    tooltip: "Information reported by users. Not verified independently.",
  },
};

export function TransparencyBadge({ source, className = "" }: Props) {
  const config = sourceConfig[source];
  const Icon = config.icon;

  return (
    <span
      className={`inline-flex items-center gap-1 text-[10px] font-medium px-2 py-0.5 rounded-md border ${config.color} ${className}`}
      title={config.tooltip}
    >
      <Icon className="h-2.5 w-2.5" />
      {config.label}
    </span>
  );
}
